#! /bin/sh
#prefix=/opt/couchbase
prefix=./
exec_prefix=${prefix}
root=${exec_prefix}/lib/python

if test -z "${PYTHONPATH}"; then
   PYTHONPATH=$root
else
   PYTHONPATH=$root:${PYTHONPATH}
fi
export PYTHONPATH

if test -z "${LD_LIBRARY_PATH}"; then
   LD_LIBRARY_PATH=${prefix}/lib
else
   LD_LIBRARY_PATH=${prefix}/lib:${LD_LIBRARY_PATH}
fi
export LD_LIBRARY_PATH

exec "$root"/`basename "$0"` "$@"
