#! /bin/sh
#prefix=/opt/couchbase
prefix=./
exec_prefix=${prefix}
root=${exec_prefix}/lib/python

if test -z "${PYTHONPATH}"; then
   PYTHONPATH=$root
else
   PYTHONPATH=$root:${PYTHONPATH}
fi
export PYTHONPATH
exec "$root"/`basename "$0"` "$@"
